version: '3'


services:
  repositories:
    image: registry:2
    volumes:
      - ./registry_volume:/var/lib/registry/
    ports:
      - 5000:5000

  registry_ui:
    image: konradkleine/docker-registry-frontend:v2
    environment:
      - ENV_DOCKER_REGISTRY_HOST="10.0.0.18"
      - ENV_DOCKER_REGISTRY_PORT=5000
    volumes:
      - ./registry_volume:/var/lib/registry/
    ports:
      - "8080:80"

